Repository Plutonium-Mcpe/pluto-wiki, pull requests merged in 2022-08, with the labels that each got.

#41 Multiple ajout (voir description)
  .idea/.gitignore
  .idea/discord.xml
  .idea/modules.xml
  .idea/pluto-wiki.iml
  .idea/vcs.xml
  docs/boss/alpha.md
  docs/boss/beta.md
  docs/boss/boss_category.md
  docs/boss/gamma.md
  docs/events-auto/chest-refill.md
  docs/events-auto/events-auto_category.md
  docs/events-auto/koth.md
  docs/events-auto/planning.md
  docs/events-auto/totem.md
  docs/help/spawner.md
  docs/jobs/bucheron.md
  docs/jobs/farmeur.md
  docs/jobs/guerrier.md
  docs/jobs/jobs_category.md
  docs/jobs/mineur.md
  docs/metiers/metiers_category.md
  php
Labels: Status: Progress, Type: Proposition, Priorité: Faible, Requiert: Relecture, Requiert: Amélioration, Type: Article, Type: Amélioration

#43 Divers corrections
  docs/events-auto/koth.md
Labels: Status: Done, Type: Bug, Type: Amélioration

#42 Modification possibilité de crée un home en WZ
  docs/commands/home.md
Labels: Status: Progress, Type: Bug, Type: Amélioration

#48 Modification graphique minage
  docs/ores/minage.md
Labels: Status: Done, Type: Amélioration

#47 Coreection spawner
  docs/help/spawner.md
Labels: Status: Progress, Type: Bug, Priorité: Faible, Requiert: Amélioration

#45 Correction totem
  docs/events-auto/totem.md
Labels: Status: Done, Type: Bug, Priorité: Faible, Requiert: Amélioration
