Repository Plutonium-Mcpe/pluto-wiki, pull requests merged in 2022-12, with the labels that each got.

#89 Delete craft_plutonim_furnace.png
  docs/blocs/furnace.md
  static/craft/craft_plutonim_furnace.png
Labels: Status: Progress, Type: Bug, Priorité: Faible, Requiert: Amélioration, Type: Craft

#93 Mise à jour Noël
  docs/blocs/christmas-gift.md
  docs/items/christmas-ball.md
  docs/items/christmas-star.md
  docs/items/fighting-stick.md
  docs/items/infinity-snowball.md
  docs/items/sandals.md
Labels: Status: Progress, Priorité: Critique, Requiert: Relecture, Type: Article

#61 issue lucky réglé
  docs/blocs/lucky-block.md
Labels: Priorité: Faible, Requiert: Relecture, Type: Amélioration, Status: Ready to merge
