Repository Plutonium-Mcpe/pluto-wiki, pull requests merged in 2022-09, with the labels that each got.

#50 maj 4.2
  docs/blocs/lucky-block.md
  docs/blocs/upgraded-obsidian.md
  docs/boss/alpha.md
  docs/boss/beta.md
  docs/boss/gamma.md
  docs/events-auto/chest-refill.md
  docs/events-auto/koth.md
  docs/events-auto/totem.md
  docs/items/dynamite.md
  docs/items/unclaim-finder.md
  static/data/custom_recipe/speed_stick.json
Labels: Status: Done, Priorité: Forte, Type: Amélioration

#71 Update lucky-trophee.md
  docs/blocs/lucky-trophee.md
Labels: Status: Progress, Priorité: Faible, Requiert: Amélioration, Type: Amélioration

#66 Ajout salon kit & parchemin, harmonisation warzone
  docs/commands/grade.md
  docs/commands/home.md
  docs/commands/kit.md
  docs/events-auto/chest-refill.md
  docs/items/key.md
  docs/items/parchment.md
  docs/items/speed-stick.md
  docs/tools/sword.md
Labels: Status: Progress, Priorité: Faible, Requiert: Relecture, Type: Article, Type: Amélioration

#70 Create box.md
  docs/help/box.md
Labels: Status: Progress, Priorité: Faible, Requiert: Amélioration, Type: Article
